### ISSUE TITLE
Link on Heroku demo is outdated

### ISSUE THREAD

**Issue by sasha42** [zachrenwick/streamlit_forecasting_app#6]
The link on [heroku](https://autoforecast-prophet.herokuapp.com/) pointing to this Github repo links to a 404 page.

![image](https://user-images.githubusercontent.com/1775702/83103557-c842fe80-a06b-11ea-906f-1e16e7c20a4f.png)

**Comment by zachrenwick** [comment]
Switched this to be hosted on streamlit cloud now!

[Streamlit Cloud ](https://share.streamlit.io/zachrenwick/streamlit_forecasting_app/app.py)

https://share.streamlit.io/zachrenwick/streamlit_forecasting_app/app.py
